# Generated by Django 5.2.4 on 2025-07-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('education', models.TextField()),
                ('experience', models.TextField()),
                ('skills', models.JSONField()),
                ('interests', models.TextField()),
                ('goals', models.TextField()),
                ('preferredField', models.CharField(max_length=100)),
                ('learningStyle', models.CharField(max_length=100)),
                ('challenges', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suggestion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
