# Generated by Django 5.2.4 on 2025-09-04 05:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('career_input', models.JSONField()),
                ('profile_snapshot', models.JSONField(blank=True, null=True)),
                ('prompt', models.TextField()),
                ('model', models.CharField(default='deepseek/deepseek-chat-v3-0324:free', max_length=100)),
                ('status', models.CharField(default='generated', max_length=32)),
                ('content', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
